# Generated by Django 5.2.4 on 2026-04-23 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lost_items/')),
                ('item', models.CharField(choices=[('umbrella', '傘'), ('stationary', '文房具'), ('phone', 'スマホ'), ('wallet', '財布'), ('book', '本(教科書・ノートなど)'), ('bottle', '水筒'), ('card', 'カード類(学生証など)'), ('other', 'その他')], max_length=30)),
                ('item_detail', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(choices=[('red', '赤'), ('blue', '青'), ('black', '黒'), ('white', '白'), ('gray', '灰'), ('brown', '茶'), ('orange', '橙'), ('yellow', '黄'), ('yellow_green', '黄緑'), ('green', '緑'), ('light_blue', '水色'), ('purple', '紫')], max_length=20)),
                ('location', models.CharField(choices=[('outdoor', '屋外'), ('classroom_building', '教室棟'), ('headquarters_building', '本部棟'), ('exchange_building', '交流棟'), ('research_building', '研究棟'), ('community_space', '有元史郎記念校友会館交流プラザ')], max_length=50)),
                ('floor', models.CharField(blank=True, choices=[('first', '1階'), ('second', '2階'), ('third', '3階'), ('fourth', '4階'), ('fifth', '5階'), ('sixth', '6階'), ('seventh', '7階')], max_length=10, null=True)),
                ('location_detail', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
