# Generated by Django 5.2.4 on 2026-04-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lost_found_Web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='floor',
            field=models.CharField(blank=True, choices=[('first', '1階'), ('second', '2階'), ('third', '3階'), ('fourth', '4階'), ('fifth', '5階'), ('sixth', '6階'), ('seventh', '7階'), ('eighth', '8階'), ('ninth', '9階'), ('tenth', '10階'), ('eleventh', '11階'), ('twelveth', '12階'), ('thirteenth', '13階'), ('fourteenth', '14階')], max_length=10, null=True),
        ),
    ]
