# Generated by Django 5.2.4 on 2026-04-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lost_found_Web', '0002_alter_post_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(choices=[('outdoor', '屋外'), ('classroom_building', '教室棟'), ('headquarters_building', '本部棟'), ('exchange_building', '交流棟'), ('research_building', '研究棟'), ('community_space', '有元史郎記念校友会館交流プラザ'), ('other', 'その他')], max_length=50),
        ),
    ]
