# Generated by Django 5.2.4 on 2026-04-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lost_found_Web', '0003_alter_post_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('open', '未解決'), ('resolved', '解決済')], default='open'),
        ),
    ]
