# Generated by Django 5.2.13 on 2026-05-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lost_found_Web', '0006_post_resolved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='item',
            field=models.CharField(choices=[('umbrella', '傘'), ('stationary', '文房具'), ('electronic_device', '電子機器および周辺機器(スマホ、イヤホンなど)'), ('valuable', '貴重品(財布、学生証など)'), ('book', '本(教科書、ノートなど)'), ('daily', '日用品(水筒、眼鏡など)'), ('other', 'その他')], max_length=30),
        ),
    ]
