# Generated by Django 5.2.13 on 2026-05-11 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lost_found_Web', '0009_alter_post_floor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='resolved_by',
        ),
        migrations.AddField(
            model_name='post',
            name='resolved_by',
            field=models.ManyToManyField(blank=True, related_name='applied_posts', to=settings.AUTH_USER_MODEL, verbose_name='申請したユーザー一覧'),
        ),
    ]
