# Generated by Django 5.2.13 on 2026-05-13 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lost_found_Web', '0011_alter_post_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='applied_by',
            field=models.ManyToManyField(blank=True, related_name='applied_posts', to=settings.AUTH_USER_MODEL, verbose_name='申請したユーザー一覧'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lost_items/'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='resolved_by',
        ),
        migrations.AddField(
            model_name='post',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_resolved', to=settings.AUTH_USER_MODEL),
        ),
    ]
